# Generated by Django 5.2.4 on 2025-08-25 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_id'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_preferences', models.JSONField(default=dict)),
                ('recent_genre_interactions', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('base_preference_weight', models.FloatField(default=0.5)),
                ('interaction_boost', models.FloatField(default=0.1)),
                ('decay_rate', models.FloatField(default=0.95)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='userinteraction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='page_context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='rating_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='recommendation_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('click', 'Clicked Movie'), ('view_detail', 'Viewed Detail Page'), ('rate', 'Rated Movie'), ('watchlist_add', 'Added to Watchlist'), ('watchlist_remove', 'Removed from Watchlist'), ('search', 'Found via Search'), ('recommendation_click', 'Clicked Recommendation')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'timestamp'], name='users_useri_user_id_b44936_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['movie', 'interaction_type'], name='users_useri_movie_i_7674a1_idx'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
