# Generated by Django 5.2.4 on 2025-08-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='The Movie Database ID for API calls', null=True),
        ),
    ]
